runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_files: ngApp/ng-app-ws/dist/ng-app/index.html
  upload: ngApp/ng-app-ws/dist/ng-app/index.html
- url: /
  static_dir: dist/ng-app